{{- if eq .Values.deployment.https true}}
apiVersion: v1
kind: Secret
data:
  {{- if eq .Values.cluster.provider "gke" }}
  key.json: {{required "gcpServiceAccount not defined" .Values.cluster.gcpServiceAccount}}
  {{- else if eq .Values.cluster.provider "azure" }}
  key.json: {{required "azureClientSecret not defined" .Values.cluster.azureClientSecret | b64enc}}
  {{- end }}
metadata:
  name: serviceAccount-{{required "sspNamespace not defined" .Values.deployment.sspNamespace}}
  namespace: {{required "sspNamespace not defined" .Values.deployment.sspNamespace}}
type: Opaque

---

apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: ssp-letsencrypt-{{required "sspNamespace not defined" .Values.deployment.sspNamespace}}
  namespace: {{required "sspNamespace not defined" .Values.deployment.sspNamespace}}
spec:
  acme:
    # server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: ssp-acme-pk-{{required "sspNamespace not defined" .Values.deployment.sspNamespace}}
    solvers:
    {{- if eq .Values.cluster.provider "gke" }}
    - dns01:
        serviceAccount:
          project: {{required "gcpProjectId not defined" .Values.cluster.gcpProjectId}}
          serviceAccountSecretRef:
            name: serviceAccount-{{required "sspNamespace not defined" .Values.deployment.sspNamespace}}
            key: key.json
    {{- else if eq .Values.cluster.provider "azure" }}
    - dns01:
        azuredns:
          clientID: {{required "azureSPAppId not defined" .Values.cluster.azureSPAppId}}
          clientSecretSecretRef:
            name: serviceAccount-{{required "sspNamespace not defined" .Values.deployment.sspNamespace}}
            key: key.json
          subscriptionID: {{required "azureSubscriptionId not defined" .Values.cluster.azureSubscriptionId}}
          tenantID: {{required "azureTenantId not defined" .Values.cluster.azureTenantId}}
          resourceGroupName: {{required "azureDnsZoneResourceGroup not defined" .Values.cluster.azureDnsZoneResourceGroup}}
          hostedZoneName: {{required "azureDnsZone not defined" .Values.cluster.azureDnsZone}}
          environment: AzurePublicCloud
    {{- end }}

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ssp-cert-{{required "sspNamespace not defined" .Values.deployment.sspNamespace}}
  namespace: {{required "sspNamespace not defined" .Values.deployment.sspNamespace}}
  annotations:
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
spec:
  dnsNames: 
    - '*.{{required "hostName not defined" .Values.deployment.hostName}}'
    - {{required "hostName not defined" .Values.deployment.hostName}}
  secretName: https-secret-{{required "sspNamespace not defined" .Values.deployment.sspNamespace}}
  issuerRef:
    name: ssp-letsencrypt-{{required "sspNamespace not defined" .Values.deployment.sspNamespace}}
{{- end }}
