apiVersion: v1
kind: Secret
data:
  key.json: {{required "clouddns not defined" .Values.clouddns}}
metadata:
  name: clouddns-{{required "sspNamespace not defined" .Values.sspNamespace}}
  namespace: {{required "sspNamespace not defined" .Values.sspNamespace}}
type: Opaque

---

apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: ssp-letsencrypt-{{required "sspNamespace not defined" .Values.sspNamespace}}
  namespace: {{required "sspNamespace not defined" .Values.sspNamespace}}
spec:
  acme:
    # server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: ssp-acme-pk-{{required "sspNamespace not defined" .Values.sspNamespace}}
    solvers:
    - dns01:
        clouddns:
          project: {{required "gcpProjectId not defined" .Values.gcpProjectId}}
          serviceAccountSecretRef:
            name: clouddns-{{required "sspNamespace not defined" .Values.sspNamespace}}
            key: key.json

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ssp-cert-{{required "sspNamespace not defined" .Values.sspNamespace}}
  namespace: {{required "sspNamespace not defined" .Values.sspNamespace}}
  annotations:
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
spec:
  dnsNames: 
    - '*.{{required "hostName not defined" .Values.hostName}}'
    - {{required "hostName not defined" .Values.hostName}}
  secretName: https-secret-{{required "sspNamespace not defined" .Values.sspNamespace}}
  issuerRef:
    name: ssp-letsencrypt-{{required "sspNamespace not defined" .Values.sspNamespace}}
