{{- if eq .Values.deployment.https true}}
apiVersion: v1
kind: Secret
data:
  {{- if eq .Values.cluster.provider "gke" }}
  key.json: {{required "gcpServiceAccount not defined" .Values.cluster.gcpServiceAccount}}
  {{- else if eq .Values.cluster.provider "azure" }}
  key.json: {{required "azureClientSecret not defined" .Values.cluster.azureClientSecret | b64enc}}
  {{- else if eq .Values.cluster.provider "aws" }}
  key.json: {{required "awsClientSecret not defined" .Values.cluster.awsClientSecret | b64enc}}
  {{- end }}
metadata:
  name: clouddns-{{required "sspNamespace not defined" .Values.sspNamespace}}
  namespace: {{required "sspNamespace not defined" .Values.sspNamespace}}
type: Opaque

---

apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: ssp-letsencrypt-{{required "sspNamespace not defined" .Values.sspNamespace}}
  namespace: {{required "sspNamespace not defined" .Values.sspNamespace}}
spec:
  acme:
    {{- if eq .Values.deployment.production true }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    privateKeySecretRef:
      name: ssp-acme-pk-{{required "sspNamespace not defined" .Values.sspNamespace}}
    solvers:
    {{- if eq .Values.cluster.provider "gke" }}
    - dns01:
        clouddns:
          project: {{required "gcpProjectId not defined" .Values.cluster.gcpProjectId}}
          serviceAccountSecretRef:
            name: clouddns-{{required "sspNamespace not defined" .Values.sspNamespace}}
            key: key.json
    {{- else if eq .Values.cluster.provider "azure" }}
    - dns01:
        azuredns:
          clientID: {{required "azureSPAppId not defined" .Values.cluster.azureSPAppId}}
          clientSecretSecretRef:
            name: clouddns-{{required "sspNamespace not defined" .Values.sspNamespace}}
            key: key.json
          subscriptionID: {{required "azureSubscriptionId not defined" .Values.cluster.azureSubscriptionId}}
          tenantID: {{required "azureTenantId not defined" .Values.cluster.azureTenantId}}
          resourceGroupName: {{required "azureDnsZoneResourceGroup not defined" .Values.cluster.azureDnsZoneResourceGroup}}
          hostedZoneName: {{required "azureDnsZone not defined" .Values.cluster.azureDnsZone}}
          environment: AzurePublicCloud
    {{- else if eq .Values.cluster.provider "aws" }}
    - selector:
        dnsZones:
          - {{required "awsDnsZone not defined" .Values.cluster.awsDnsZone}}
      dns01:
        route53:
          region: {{required "awsRegion not defined" .Values.cluster.awsRegion}}
          accessKeyID: {{required "awsAccessKeyId not defined" .Values.cluster.awsAccessKeyId}}
          secretAccessKeySecretRef:
            name: clouddns-{{required "sspNamespace not defined" .Values.sspNamespace}}
            key: key.json
          {{- if .Values.cluster.awsRole }}
          role: {{.Values.cluster.awsRole}}
          {{- end }}
    {{- end }}

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ssp-cert-{{required "sspNamespace not defined" .Values.sspNamespace}}
  namespace: {{required "sspNamespace not defined" .Values.sspNamespace}}
  annotations:
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
spec:
  dnsNames: 
    - '*.{{required "hostName not defined" .Values.hostName}}'
    - {{required "hostName not defined" .Values.hostName}}
  secretName: https-secret-{{required "sspNamespace not defined" .Values.sspNamespace}}
  issuerRef:
    name: ssp-letsencrypt-{{required "sspNamespace not defined" .Values.sspNamespace}}
{{- end }}
