kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ssp-service-db-np-{{required "sspNamespace not defined" .Values.sspNamespace}}
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector:
    matchLabels:
      sspNamespace: {{required "sspNamespace not defined" .Values.sspNamespace}}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          sspNamespace: {{required "sspNamespace not defined" .Values.sspNamespace}}

---

apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: ssp-vs-{{required "sspNamespace not defined" .Values.sspNamespace}}
  namespace: {{required "sspNamespace not defined" .Values.sspNamespace}}
spec:
  {{- if eq .Values.deployment.https true}}
  tls:
    secret: https-secret-{{required "sspNamespace not defined" .Values.sspNamespace}}
  {{- end }}
  host: {{required "hostName not defined" .Values.hostName}}
  upstreams:
  - name: web
    service: ssp-service-{{required "sspNamespace not defined" .Values.sspNamespace}}
    port: 80
  routes:
  - path: /
    action:
      pass: web
