apiVersion: v1
kind: Secret
data:
  config.ini: {{(tpl (.Files.Get "ssp-config.ini") .) | b64enc}}
metadata:
  name: ssp-config
  namespace: {{required "sspNamespace not defined" .Values.sspNamespace}}
type: Opaque

---

apiVersion: v1
kind: Secret
data:
  values.yaml: {{(tpl (.Files.Get "sugarizer-chart-values.yaml") .) | b64enc}}
metadata:
  name: sugarizer-chart-values
  namespace: {{required "sspNamespace not defined" .Values.sspNamespace}}
type: Opaque
