apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssp-service-account-{{required "sspNamespace not defined" .Values.sspNamespace}}
  namespace: {{required "sspNamespace not defined" .Values.sspNamespace}}
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ssp-clusterrole-{{required "sspNamespace not defined" .Values.sspNamespace}}
  namespace: {{required "sspNamespace not defined" .Values.sspNamespace}}
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services", "secrets", "namespaces", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["k8s.nginx.org"]
    resources: ["virtualservers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates", "issuers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ssp-clusterrolebinding-{{required "sspNamespace not defined" .Values.sspNamespace}}
  namespace: {{required "sspNamespace not defined" .Values.sspNamespace}}
subjects:
  - kind: ServiceAccount
    name: ssp-service-account-{{required "sspNamespace not defined" .Values.sspNamespace}}
    namespace: {{required "sspNamespace not defined" .Values.sspNamespace}}
roleRef:
  kind: ClusterRole
  name: ssp-clusterrole-{{required "sspNamespace not defined" .Values.sspNamespace}}
  apiGroup: rbac.authorization.k8s.io
